name: Build Kivy APK

on:
  push:
    branches: [ main, master ] # Adjust branch name if needed
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Using Python 3.9

    # Cache Buildozer global directory (Good practice)
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    # Install basic system dependencies + JDK (Keep this)
    - name: Install system dependencies and JDK
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git \
          zip \
          unzip \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libffi-dev \
          libssl-dev \
          liblzma-dev \
          zlib1g-dev \
          python3-pip \
          python3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          openjdk-17-jdk # Ensure JDK 17 is installed
        # Clean apt cache to save space
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

    # --- NEW: Install Android SDK Command-line Tools ---
# --- REVISED: Install Android SDK Command-line Tools ---
    - name: Install Android SDK Command-line Tools
      env:
        CMDLINE_TOOLS_VERSION: "11076708" # Use a known recent version or check Android Studio site
        ANDROID_SDK_ROOT: "${{ github.workspace }}/android-sdk"
      run: |
        echo "Downloading Android SDK command-line tools version ${CMDLINE_TOOLS_VERSION}..."
        mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
        wget -q "https://dl.google.com/android/repository/commandlinetools-linux-${CMDLINE_TOOLS_VERSION}_latest.zip" -O cmdline-tools.zip

        echo "Unzipping tools..."
        unzip -q cmdline-tools.zip -d "${ANDROID_SDK_ROOT}/cmdline-tools"
        # The zip usually contains a 'cmdline-tools' directory inside. We need to move its contents
        # into 'cmdline-tools/latest' to match the expected structure for sdkmanager.
        # Check if the nested directory exists before moving
        if [ -d "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools" ]; then
          echo "Moving nested cmdline-tools contents to cmdline-tools/latest..."
          # Create the 'latest' directory
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
          # Move everything from the nested directory to 'latest'
          mv "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools/"* "${ANDROID_SDK_ROOT}/cmdline-tools/latest/"
          # Remove the now empty nested directory
          rm -rf "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools"
        else
          echo "WARN: Expected nested 'cmdline-tools' directory not found after unzip. Structure might be different."
          # Attempt to handle case where it unzips directly (less common now)
          # Assuming 'bin', 'lib' etc. are directly under $ANDROID_SDK_ROOT/cmdline-tools
          if [ -d "${ANDROID_SDK_ROOT}/cmdline-tools/bin" ]; then
             echo "Assuming direct unzip structure. Moving contents to 'latest'."
             # Create 'latest' and move existing top-level items into it
             mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
             # Find all files/dirs directly under cmdline-tools (excluding 'latest' itself) and move them
             find "${ANDROID_SDK_ROOT}/cmdline-tools" -maxdepth 1 -mindepth 1 ! -name 'latest' -exec mv -t "${ANDROID_SDK_ROOT}/cmdline-tools/latest/" {} +
          else
            echo "ERROR: Could not determine command-line tools structure after unzip."
            exit 1
          fi
        fi

        rm cmdline-tools.zip

        # Define the standard paths
        CMDLINE_TOOLS_PATH="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin"
        PLATFORM_TOOLS_PATH="${ANDROID_SDK_ROOT}/platform-tools"

        echo "Adding SDK paths to environment..."
        echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV
        # Add the correct paths to the system PATH for subsequent steps
        echo "PATH=${PATH}:${CMDLINE_TOOLS_PATH}:${PLATFORM_TOOLS_PATH}" >> $GITHUB_ENV

        echo "Android SDK Root: ${ANDROID_SDK_ROOT}"
        echo "Updated PATH: ${PATH}:${CMDLINE_TOOLS_PATH}:${PLATFORM_TOOLS_PATH}"

        echo "Verifying sdkmanager installation..."
        # Verify the sdkmanager exists at the expected 'latest' path
        ls -l "${CMDLINE_TOOLS_PATH}/sdkmanager"
        if [ $? -ne 0 ]; then
          echo "ERROR: sdkmanager not found at ${CMDLINE_TOOLS_PATH}/sdkmanager"
          echo "Listing contents of ${ANDROID_SDK_ROOT}/cmdline-tools/latest:"
          ls -lR "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
          exit 1
        fi
        echo "sdkmanager found."

    # --- NEW: Install Android SDK Platforms, Build-Tools, and NDK ---
    - name: Install Android SDK components and NDK
      env:
        # --- IMPORTANT: Adjust these versions based on your buildozer.spec ---
        ANDROID_PLATFORM_VERSION: "34"        # Match 'android.api' in buildozer.spec
        ANDROID_BUILD_TOOLS_VERSION: "34.0.0" # Match 'android.build_tools_version' or use a recent one
        ANDROID_NDK_VERSION: "25.2.9519653"   # Match 'android.ndk_version' or a compatible one (check Buildozer docs)
      run: |
        echo "Installing Android SDK platform-tools, platforms, build-tools, and NDK..."
        echo "Using ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
        echo "Listing available packages (optional)..."
        # sdkmanager --list || echo "Listing failed, continuing..." # Can be very verbose
        echo "Accepting licenses..."
        yes | sdkmanager --licenses > /dev/null || echo "Failed to accept licenses. Check SDK setup." # Suppress verbose license output
        echo "Installing components..."
        sdkmanager "platform-tools" "platforms;android-${ANDROID_PLATFORM_VERSION}" "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "ndk;${ANDROID_NDK_VERSION}"
        echo "NDK should now be at $ANDROID_SDK_ROOT/ndk/${ANDROID_NDK_VERSION}"
        # Ensure the installed NDK path is also set for Buildozer if needed explicitly
        # Buildozer usually finds it within ANDROID_SDK_ROOT, but setting ANDROID_NDK_HOME is safer
        echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV
        echo "Verifying NDK installation..."
        ls -l $ANDROID_SDK_ROOT/ndk/ # See installed NDK versions
        ls -l $ANDROID_SDK_ROOT/build-tools/ # See installed build-tools versions
        echo "Verifying aidl..."
        ls -l $ANDROID_SDK_ROOT/build-tools/${ANDROID_BUILD_TOOLS_VERSION}/aidl || echo "aidl still not found!"

    # Install/Upgrade Python dependencies (Buildozer, Cython)
    - name: Install/Upgrade buildozer and cython
      run: |
        pip install --upgrade pip setuptools wheel
        pip install cython # Often required
        pip install --upgrade buildozer # Ensure latest buildozer is used

    # Clean previous build artifacts (Keep this)
    - name: Clean previous build artifacts
      run: |
        echo "Running buildozer clean..."
        buildozer clean || echo "Clean failed or directory didn't exist, continuing..."

    # Build APK with Buildozer (Keep this)
    - name: Build APK with Buildozer
      run: |
        # Use -v for verbose output. Check ANDROID_SDK_ROOT and ANDROID_NDK_HOME are set
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
        buildozer -v android debug # Use -v for verbose output

    # Upload APK artifact (Keep this)
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: captcha-app-apk # Consider making this dynamic if needed
        path: bin/*.apk # Path to the generated APK file(s)
