name: Build Kivy APK

on:
  push:
    branches: [ main, master ] # Adjust branch name if needed
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Using Python 3.9

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libffi-dev \
          libssl-dev \
          liblzma-dev \
          zlib1g-dev \
          python3-pip \
          python3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          openjdk-17-jdk # Ensure JDK 17 is installed

    - name: Install/Upgrade buildozer and cython
      run: |
        pip install --upgrade pip setuptools wheel
        pip install cython # Often required
        pip install --upgrade buildozer # Ensure latest buildozer is used

    - name: Clean previous build artifacts # ADDED CLEAN STEP
      run: |
        echo "Running buildozer clean..."
        buildozer clean || echo "Clean failed or directory didn't exist, continuing..." # Run clean, continue even if it fails (e.g., first run)

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug # Use -v for verbose output, helpful for debugging

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: captcha-app-apk
        path: bin/*.apk # Path to the generated APK file(s)
