name: Build Kivy APK

# Controls when the action will run.
# Triggers the workflow on push events but only for the main branch
# Also allows manual triggering from the Actions tab
on:
  push:
    branches: [ main, master ] # Adjust branch name if needed
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository # Checks-out your repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v4

    - name: Set up Python # Sets up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Choose a Python version (e.g., 3.9 or 3.10)

    - name: Cache Buildozer global directory # Cache dependencies to speed up builds
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install dependencies # Install system dependencies needed by buildozer/p4a
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libffi-dev \
          libssl-dev \
          liblzma-dev \
          zlib1g-dev \
          python3-pip \
          python3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          openjdk-17-jdk # Ensure JDK is installed (adjust version if needed)

    - name: Install buildozer and cython # Install buildozer and required Cython
      run: |
        pip install --upgrade pip setuptools wheel
        pip install cython # Often required
        pip install buildozer

    - name: Build APK with Buildozer # Run buildozer to create the debug APK
      run: |
        buildozer android debug # Use 'release' for a release build (requires signing setup)

    - name: Upload APK artifact # Upload the generated APK file as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: captcha-app-apk # Name of the artifact zip file
        path: bin/*.apk # Path to the generated APK file(s)
